### ISSUE TITLE
Enable Kiali to visualize iter8 experiments

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali-ui#1]
KIali UI is a web-based graphical user interface to view service graphs of the mesh and your Istio configuration objects.
Integration with Iter8  provides UI for managing and monitoring experiment objects for iter8.

Design consideration for 
- [ ] Summary List #2 
- [ ] Detail page, include tab design #3
- [ ] Create New Experiment, Left Nav - Experiment, Service? #4
- [ ] Metric Types #5 
- [ ] Possible Action - Create, Pause, Roll-forward, Roll-Back #7

**Comment by sriumcp** [comment]
Done.
